# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python application

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Lint with flake8
      run: |
        # stop the build if there are Python syntax errors or undefined names
        # ignores: 
        # - E402 "module level import not at top of file" (isolate C imports in case python alternatives exist)
        # - W503 "line break before binary operator" (we enforce line breaks before operators, to follow black style, and penalise line breaks after)
        # - F811 "redefinition of unused name from line N" (breaks quantity objects)
        # - E203 "whitespace before ‘,’, ‘;’, or ‘:’" (conflicts with black formatting of array indexing, `:`)
        flake8 . --count --ignore=E402,W503,F811,E203 --max-line-length=79 --show-source --statistics
    - name: Test with pytest
      run: |
        pytest
